[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
healthcheckInterval = 30
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[nixpacks]
nodejs = "18"
